//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace city_scraper_api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityScraperDb : DbContext
    {
        public CityScraperDb()
            : base("name=CityScraperDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerGame> PlayerGames { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MergeSummary> MergeSummaries { get; set; }
        public virtual DbSet<ScraperSummary> ScraperSummaries { get; set; }
        public virtual DbSet<AwayRecord> AwayRecords { get; set; }
        public virtual DbSet<HomeRecord> HomeRecords { get; set; }
        public virtual DbSet<TotalRecord> TotalRecords { get; set; }
        public virtual DbSet<TotalStat> TotalStats { get; set; }
    }
}
