//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace city_scraper_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public System.DateTime date { get; set; }
        public string home { get; set; }
        public Nullable<int> HomeTeamScore { get; set; }
        public Nullable<int> AwayTeamScore { get; set; }
        public string away { get; set; }
    }
}
