//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace city_scraper_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalStat
    {
        public int Id { get; set; }
        public string Player { get; set; }
        public string School { get; set; }
        public Nullable<int> total_goals { get; set; }
        public Nullable<int> total_assists { get; set; }
        public Nullable<int> total { get; set; }
        public int SchoolId { get; set; }
        public Nullable<double> Goals_Per_Game { get; set; }
        public Nullable<double> Percentage_Games_With_Goal { get; set; }
        public Nullable<long> Rank { get; set; }
    }
}
