//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace city_scraper_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalRecord
    {
        public string name { get; set; }
        public int AwayTeamId { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Ties { get; set; }
        public Nullable<int> Loses { get; set; }
    }
}
